import { YoutubeTranscript } from "youtube-transcript";       // kept for reference — commented out below
import { getSubtitles } from "youtube-caption-extractor";    // kept for reference — commented out below

export interface VideoMetadata {
  videoId: string;
  title: string;
  duration: number;
  thumbnailUrl: string;
  channelName: string;
}

export interface TranscriptEntry {
  text: string;
  offset: number;
  duration: number;
}

export function extractVideoId(url: string): string | null {
  const patterns = [
    /(?:youtube\.com\/watch\?v=|youtu\.be\/|youtube\.com\/embed\/)([a-zA-Z0-9_-]{11})/,
    /^([a-zA-Z0-9_-]{11})$/,
  ];
  for (const pattern of patterns) {
    const match = url.match(pattern);
    if (match) return match[1];
  }
  return null;
}

export function validateYouTubeUrl(url: string): { valid: boolean; error?: string } {
  if (!url || url.trim() === "") {
    return { valid: false, error: "Please enter a YouTube URL." };
  }
  const videoId = extractVideoId(url);
  if (!videoId) {
    return { valid: false, error: "Invalid YouTube URL. Please use a standard youtube.com or youtu.be link." };
  }
  return { valid: true };
}

/** Map youtube-caption-extractor rows to our transcript format. */
function mapExtractorSubtitles(
  subs: { start: string; dur: string; text: string }[]
): TranscriptEntry[] {
  return subs
    .map((s) => ({
      text: s.text.trim(),
      offset: Number.parseFloat(s.start) || 0,
      duration: Math.max(0.05, Number.parseFloat(s.dur) || 0.2),
    }))
    .filter((e) => e.text.length > 0);
}

/**
 * Fallback when `youtube-transcript` breaks (YouTube HTML/API changes are common).
 * Uses InnerTube-style fetches and caption XML, including on Vercel where the old library often fails.
 */
/**
 * Default Piped API bases (comma-free origins). Public instances rotate availability;
 * we try several before failing. Override entirely with PIPED_BACKEND_URLS in production.
 * @see https://github.com/TeamPiped/Piped/wiki/List-of-instances
 */
const DEFAULT_PIPED_BACKENDS = [
  "https://pipedapi.kavin.rocks",
  "https://pipedapi.adminforge.de",
  "https://pipedapi.moomoo.me",
  "https://pipedapi.tokhmi.xyz",
  "https://api.piped.private.coffee",
];

function getPipedBackendList(): string[] {
  const fromEnv = process.env.PIPED_BACKEND_URLS?.split(",").map((s) => s.trim()).filter(Boolean);
  return fromEnv && fromEnv.length > 0 ? fromEnv : DEFAULT_PIPED_BACKENDS;
}

function isLikelyServerlessEgress(): boolean {
  return Boolean(
    process.env.VERCEL ||
      process.env.AWS_LAMBDA_FUNCTION_NAME ||
      process.env.AWS_EXECUTION_ENV ||
      process.env.K_SERVICE
  );
}

function sleep(ms: number): Promise<void> {
  return new Promise((r) => setTimeout(r, ms));
}

function ttmlTimeToSeconds(ts: string): number {
  const t = ts.trim();
  const parts = t.split(":");
  if (parts.length === 1) return parseFloat(parts[0]) || 0;
  if (parts.length === 2) return (parseInt(parts[0], 10) || 0) * 60 + (parseFloat(parts[1]) || 0);
  if (parts.length === 3) {
    return (
      (parseInt(parts[0], 10) || 0) * 3600 +
      (parseInt(parts[1], 10) || 0) * 60 +
      (parseFloat(parts[2]) || 0)
    );
  }
  return 0;
}

function decodeXmlEntities(raw: string): string {
  return raw
    .replace(/&amp;/g, "&")
    .replace(/&lt;/g, "<")
    .replace(/&gt;/g, ">")
    .replace(/&quot;/g, '"')
    .replace(/&#39;/g, "'")
    .replace(/&nbsp;/g, " ");
}

/** Parses YouTube TTML from Piped subtitle URLs (mimeType application/ttml+xml). */
function parseTtmlToTranscript(xml: string): TranscriptEntry[] {
  const out: TranscriptEntry[] = [];
  const blockRe = /<p\b([^>]+)>([\s\S]*?)<\/p>/gi;
  let m: RegExpExecArray | null;
  while ((m = blockRe.exec(xml)) !== null) {
    const begin = /(?:^|\s)begin="([^"]+)"/i.exec(m[1])?.[1];
    const end = /(?:^|\s)end="([^"]+)"/i.exec(m[1])?.[1];
    if (!begin || !end) continue;
    const start = ttmlTimeToSeconds(begin);
    const endSec = ttmlTimeToSeconds(end);
    const rawInner = m[2].replace(/<br\s*\/?>/gi, " ").replace(/<[^>]+>/g, "");
    const text = decodeXmlEntities(rawInner).replace(/\s+/g, " ").trim();
    if (!text || endSec <= start) continue;
    out.push({ text, offset: start, duration: endSec - start });
  }
  return out;
}

type PipedSubtitleTrack = {
  url: string;
  mimeType?: string;
  code?: string;
  name?: string;
  autoGenerated?: boolean;
};

/** Sort all subtitle tracks by preference (not only the best one). */
function sortPipedSubtitleTracks(tracks: PipedSubtitleTrack[]): PipedSubtitleTrack[] {
  const score = (s: PipedSubtitleTrack) => {
    const code = (s.code ?? "").toLowerCase();
    let sc = 0;
    if (code === "en" || code.startsWith("en-")) sc += 200;
    if ((s.name ?? "").toLowerCase().includes("english")) sc += 100;
    if (s.mimeType?.includes("ttml") || s.mimeType?.includes("vtt")) sc += 10;
    if (s.autoGenerated) sc -= 2;
    return sc;
  };
  return [...tracks].sort((a, b) => score(b) - score(a));
}

/** WebVTT timestamp: HH:MM:SS.mmm or MM:SS.mmm */
function parseVttTimestamp(raw: string): number {
  const t = raw.trim().split(/\s+/)[0];
  const parts = t.split(":");
  if (parts.length === 3) {
    const ms = parts[2].split(".");
    const sec = parseInt(parts[0], 10) * 3600 + parseInt(parts[1], 10) * 60 + (parseInt(ms[0], 10) || 0);
    const frac = ms[1] ? parseInt(ms[1].padEnd(3, "0").slice(0, 3), 10) / 1000 : 0;
    return sec + frac;
  }
  if (parts.length === 2) {
    const ms = parts[1].split(".");
    const sec = parseInt(parts[0], 10) * 60 + (parseInt(ms[0], 10) || 0);
    const frac = ms[1] ? parseInt(ms[1].padEnd(3, "0").slice(0, 3), 10) / 1000 : 0;
    return sec + frac;
  }
  return 0;
}

function isVttCueLine(trimmed: string): boolean {
  return trimmed.includes("-->") && /^\d/.test(trimmed);
}

/** Parse WebVTT body (Piped often serves text/vtt). Supports optional cue identifiers and NOTE blocks. */
function parseWebVttToTranscript(vtt: string): TranscriptEntry[] {
  const out: TranscriptEntry[] = [];
  const norm = vtt.replace(/\r\n/g, "\n");
  const lines = norm.split("\n");

  let i = 0;
  while (i < lines.length) {
    const line = lines[i].trim();
    if (line.startsWith("WEBVTT") || line.startsWith("NOTE") || line === "" || line.startsWith("STYLE") || line.startsWith("REGION")) {
      i++;
      continue;
    }
    if (isVttCueLine(line)) {
      const arrow = line.split("-->").map((s) => s.trim());
      if (arrow.length >= 2) {
        const start = parseVttTimestamp(arrow[0]);
        const end = parseVttTimestamp(arrow[1]);
        const textParts: string[] = [];
        i++;
        while (i < lines.length && lines[i].trim() !== "" && !isVttCueLine(lines[i].trim())) {
          textParts.push(lines[i]);
          i++;
        }
        const text = textParts.join(" ").replace(/<[^>]+>/g, " ").replace(/\s+/g, " ").trim();
        if (text && end > start) {
          out.push({ text: decodeXmlEntities(text), offset: start, duration: Math.max(0.05, end - start) });
        }
        continue;
      }
    }
    if (/^\d+$/.test(line) && i + 1 < lines.length && isVttCueLine(lines[i + 1].trim())) {
      i++;
      continue;
    }
    i++;
  }
  return out;
}

function parseSubtitlePayload(raw: string, mimeHint: string, contentType: string): TranscriptEntry[] {
  const mime = `${mimeHint} ${contentType}`.toLowerCase();
  const head = raw.trimStart().slice(0, 200).toLowerCase();
  if (mime.includes("vtt") || head.startsWith("webvtt")) {
    const v = parseWebVttToTranscript(raw);
    if (v.length > 0) return v;
  }
  if (mime.includes("ttml") || raw.trimStart().startsWith("<?xml") || raw.includes("<tt ") || raw.includes("<p ")) {
    const t = parseTtmlToTranscript(raw);
    if (t.length > 0) return t;
  }
  return [];
}

/**
 * Loads captions via a Piped-compatible API (/streams/:id → subtitle proxy URLs).
 * Often works on Vercel when direct youtube.com transcript fetches return 403/empty because
 * the proxy uses different egress than raw datacenter scrapers.
 */
async function fetchTranscriptViaPipedBackends(videoId: string): Promise<TranscriptEntry[] | null> {
  const headers = {
    Accept: "application/json",
    "User-Agent": "Lecturemate/1.0 (transcript; +https://github.com/TeamPiped/Piped)",
  };

  const backends = getPipedBackendList();
  for (let b = 0; b < backends.length; b++) {
    const apiBase = backends[b].replace(/\/$/, "");
    try {
      const streamsUrl = `${apiBase}/streams/${videoId}`;
      let res = await fetch(streamsUrl, {
        signal: AbortSignal.timeout(22000),
        headers,
      });
      if (res.status === 429 || res.status === 503) {
        await sleep(400 + b * 200);
        res = await fetch(streamsUrl, { signal: AbortSignal.timeout(22000), headers });
      }
      if (!res.ok) continue;
      const data = (await res.json()) as { subtitles?: PipedSubtitleTrack[]; error?: string };
      if (data.error || !data.subtitles?.length) continue;

      const ordered = sortPipedSubtitleTracks(data.subtitles);
      for (const track of ordered.slice(0, 6)) {
        if (!track?.url) continue;
        try {
          const subRes = await fetch(track.url, {
            signal: AbortSignal.timeout(50000),
            headers: { ...headers, Accept: "*/*" },
          });
          if (!subRes.ok) continue;
          const raw = await subRes.text();
          if (!raw.trim()) continue;
          const ct = subRes.headers.get("content-type") ?? "";
          const entries = parseSubtitlePayload(raw, track.mimeType ?? "", ct);
          if (entries.length > 0) return entries;
        } catch {
          /* next track */
        }
      }
    } catch {
      /* try next backend */
    }
  }
  return null;
}

async function fetchTranscriptViaExtractor(videoId: string): Promise<TranscriptEntry[] | null> {
  const languagesToTry = [
    "en",
    "en-US",
    "en-GB",
    "hi",
    "bn",
    "ta",
    "te",
    "mr",
    "gu",
    "kn",
    "ml",
    "es",
    "fr",
    "de",
    "pt",
    "it",
    "nl",
    "pl",
    "ru",
    "uk",
    "zh",
    "zh-Hans",
    "ja",
    "ko",
    "vi",
    "th",
    "id",
    "ar",
    "tr",
  ];
  for (const lang of languagesToTry) {
    try {
      const subs = await getSubtitles({ videoID: videoId, lang });
      if (subs.length > 0) return mapExtractorSubtitles(subs);
    } catch {
      /* try next language */
    }
  }
  return null;
}

/**
 * Calls our lightweight transcript proxy (deployed on Railway/Render).
 * Set TRANSCRIPT_PROXY_URL in env, e.g. https://transcript-proxy-production.up.railway.app
 */
async function fetchTranscriptViaProxy(videoId: string): Promise<TranscriptEntry[] | null> {
  const proxyBase = process.env.TRANSCRIPT_PROXY_URL;
  if (!proxyBase) return null;
  try {
    const res = await fetch(`${proxyBase.replace(/\/$/, "")}/transcript/${videoId}`, {
      signal: AbortSignal.timeout(30000),
      headers: { Accept: "application/json" },
    });
    if (!res.ok) return null;
    const data = (await res.json()) as { transcript?: TranscriptEntry[] };
    if (data.transcript && data.transcript.length > 0) return data.transcript;
  } catch {
    /* proxy unavailable */
  }
  return null;
}

type SupadataChunk = { text: string; offset: number; duration: number; lang?: string };

/**
 * Polls a Supadata async job until it completes or times out (60s).
 * Large videos (>20 min) return HTTP 202 + jobId instead of the transcript directly.
 */
async function pollSupadataJob(apiKey: string, jobId: string): Promise<TranscriptEntry[]> {
  const maxAttempts = 18; // 18 × 1s = 18s max polling, keeps each video under 25s total
  for (let i = 0; i < maxAttempts; i++) {
    await sleep(1000);
    const res = await fetch(`https://api.supadata.ai/v1/transcript/${jobId}`, {
      headers: { "x-api-key": apiKey },
      signal: AbortSignal.timeout(10000),
    });
    if (!res.ok) {
      console.warn(`[pollSupadataJob] poll ${i + 1} returned HTTP ${res.status}`);
      continue;
    }
    const data = await res.json() as {
      status?: string;
      content?: SupadataChunk[] | string;
      error?: string;
    };
    console.log(`[pollSupadataJob] attempt ${i + 1}  status=${data.status}`);
    if (data.status === "completed") {
      if (!data.content) throw new Error("Supadata job completed but content is empty.");
      if (typeof data.content === "string") {
        return [{ text: data.content, offset: 0, duration: 0 }];
      }
      return data.content.map((c) => ({
        text: c.text,
        offset: c.offset / 1000,
        duration: c.duration / 1000,
      }));
    }
    if (data.status === "failed") throw new Error(`Supadata job failed: ${data.error ?? "unknown"}`);
  }
  throw new Error("Supadata job timed out after 18 seconds.");
}

/**
 * Fetches transcript via Supadata API (https://supadata.ai).
 * Handles both immediate (HTTP 200) and async (HTTP 202 + jobId) responses.
 * Uses mode=native to only fetch existing captions (1 credit).
 * Set SUPADATA_API_KEY in env.
 */
async function fetchTranscriptViaSupadata(videoId: string): Promise<TranscriptEntry[]> {
  const apiKey = process.env.SUPADATA_API_KEY;
  if (!apiKey) throw new Error("SUPADATA_API_KEY is not set. Add it to your environment variables.");

  const videoUrl = `https://www.youtube.com/watch?v=${videoId}`;
  const endpoint =
    `https://api.supadata.ai/v1/transcript` +
    `?url=${encodeURIComponent(videoUrl)}&lang=en&mode=native`;

  console.log(`[fetchTranscriptViaSupadata] GET ${endpoint}`);
  const res = await fetch(endpoint, {
    headers: { "x-api-key": apiKey },
    signal: AbortSignal.timeout(20000), // 20s for initial request; async jobs then poll for up to 18s
  });

  if (!res.ok) {
    const body = await res.text().catch(() => "");
    throw new Error(`Supadata API error: HTTP ${res.status} — ${body.slice(0, 300)}`);
  }

  // HTTP 202 = async job for long videos
  if (res.status === 202) {
    const { jobId } = await res.json() as { jobId: string };
    console.log(`[fetchTranscriptViaSupadata] async job started  jobId=${jobId}`);
    return pollSupadataJob(apiKey, jobId);
  }

  const data = await res.json() as {
    content?: SupadataChunk[] | string;
    lang?: string;
    availableLangs?: string[];
  };

  console.log(`[fetchTranscriptViaSupadata] received  lang=${data.lang}  availableLangs=${data.availableLangs?.join(",")}`);

  if (!data.content || (Array.isArray(data.content) && data.content.length === 0)) {
    throw new Error("Supadata returned empty transcript content.");
  }

  // Plain-text fallback (shouldn't happen with text=false default, but guard it)
  if (typeof data.content === "string") {
    return [{ text: data.content, offset: 0, duration: 0 }];
  }

  const entries = data.content.map((c) => ({
    text: c.text,
    offset: c.offset / 1000,   // ms → seconds
    duration: c.duration / 1000,
  }));
  console.log(`[fetchTranscriptViaSupadata] ✅ ${entries.length} entries  lang=${data.lang}`);
  return entries;
}

export async function fetchTranscript(videoId: string): Promise<TranscriptEntry[]> {
  // ── Primary: Supadata managed API ────────────────────────────────────────
  // Reliably bypasses YouTube's datacenter IP blocks (Vercel, Railway, etc.).
  // Free tier: 100 transcripts/month — https://supadata.ai
  try {
    const entries = await fetchTranscriptViaSupadata(videoId);
    if (entries.length > 0) return entries;
  } catch (err) {
    console.error(`[fetchTranscript] Supadata failed:`, err instanceof Error ? err.message : err);
    throw err;
  }

  // ── Commented-out fallback strategies (re-enable if needed) ───────────────

  // // Strategy: YouTube Data API v3 captions.download (requires OAuth for 3rd-party videos)
  // try {
  //   const entries = await fetchTranscriptViaYouTubeApi(videoId);
  //   if (entries.length > 0) return entries;
  // } catch (err) { console.warn("[fetchTranscript] YouTube API failed:", err); }

  // // Strategy: youtube-transcript library (blocked on Vercel/Railway)
  // try {
  //   const t = await YoutubeTranscript.fetchTranscript(videoId);
  //   if (t.length > 0) return t.map((e) => ({ text: e.text, offset: e.offset / 1000, duration: e.duration / 1000 }));
  // } catch (err) { console.warn("[fetchTranscript] youtube-transcript failed:", err); }

  // // Strategy: Piped proxy backends
  // const viaPiped = await fetchTranscriptViaPipedBackends(videoId);
  // if (viaPiped && viaPiped.length > 0) return viaPiped;

  // // Strategy: youtube-caption-extractor (InnerTube)
  // const viaExtractor = await fetchTranscriptViaExtractor(videoId);
  // if (viaExtractor && viaExtractor.length > 0) return viaExtractor;

  throw new Error("No transcript entries returned.");
}

/** Parse ISO 8601 duration strings returned by the YouTube Data API v3 (e.g. "PT1H4M52S"). */
function parseIso8601Duration(d: string): number {
  const m = d.match(/PT(?:(\d+)H)?(?:(\d+)M)?(?:(\d+(?:\.\d+)?)S)?/);
  if (!m) return 0;
  return (parseInt(m[1] ?? "0", 10) * 3600) +
         (parseInt(m[2] ?? "0", 10) * 60) +
         (parseFloat(m[3] ?? "0") || 0);
}

/**
 * Calls YouTube Data API v3 `captions.list` to discover which caption language
 * codes are actually available. Returns the codes sorted by preference (manual
 * English first, then auto-generated, then others). Falls back to an empty array
 * when the API key is absent or the call fails.
 *
 * Note: `captions.download` requires OAuth; this only lists available tracks so
 * the transcript fallback chain can prioritise the right languages.
 */
export async function fetchCaptionLanguages(videoId: string): Promise<string[]> {
  const apiKey = process.env.YOUTUBE_API_KEY;
  if (!apiKey) return [];
  try {
    const url = `https://www.googleapis.com/youtube/v3/captions?part=snippet&videoId=${videoId}&key=${encodeURIComponent(apiKey)}`;
    const res = await fetch(url, { signal: AbortSignal.timeout(8000) });
    if (!res.ok) return [];
    const data = await res.json() as {
      items?: { snippet: { language: string; trackKind: string } }[];
    };
    const items = data.items ?? [];
    // Sort: manual English tracks first, then other manuals, then auto-generated
    items.sort((a, b) => {
      const score = (s: { language: string; trackKind: string }) => {
        let sc = 0;
        if (s.trackKind !== "asr") sc += 100;
        const lang = s.language.toLowerCase();
        if (lang === "en" || lang.startsWith("en-")) sc += 50;
        return sc;
      };
      return score(b.snippet) - score(a.snippet);
    });
    return items.map((i) => i.snippet.language);
  } catch {
    return [];
  }
}

/**
 * Fetches video metadata using YouTube Data API v3 `videos.list` when
 * `YOUTUBE_API_KEY` is set. Falls back to the oEmbed endpoint (no key required)
 * so development without a key still works. The Data API provides accurate
 * duration and higher-resolution thumbnail choices.
 */
export async function fetchVideoMetadata(videoId: string): Promise<VideoMetadata> {
  const apiKey = process.env.YOUTUBE_API_KEY;

  if (apiKey) {
    try {
      const url =
        `https://www.googleapis.com/youtube/v3/videos` +
        `?part=snippet,contentDetails` +
        `&id=${encodeURIComponent(videoId)}` +
        `&key=${encodeURIComponent(apiKey)}`;
      const res = await fetch(url, { signal: AbortSignal.timeout(8000) });
      if (res.ok) {
        const data = await res.json() as {
          items?: {
            snippet: {
              title: string;
              channelTitle: string;
              thumbnails: {
                maxres?: { url: string };
                high?: { url: string };
                medium?: { url: string };
                default?: { url: string };
              };
            };
            contentDetails: { duration: string };
          }[];
        };
        const item = data.items?.[0];
        if (item) {
          const { snippet, contentDetails } = item;
          const thumbnailUrl =
            snippet.thumbnails.maxres?.url ??
            snippet.thumbnails.high?.url ??
            snippet.thumbnails.medium?.url ??
            `https://img.youtube.com/vi/${videoId}/maxresdefault.jpg`;
          return {
            videoId,
            title: snippet.title ?? "YouTube Lecture",
            channelName: snippet.channelTitle ?? "Unknown Channel",
            duration: parseIso8601Duration(contentDetails.duration),
            thumbnailUrl,
          };
        }
      }
    } catch {
      // fall through to oEmbed
    }
  }

  // oEmbed fallback (no API key required)
  const oembedUrl = `https://www.youtube.com/oembed?url=https://www.youtube.com/watch?v=${videoId}&format=json`;
  let title = "YouTube Lecture";
  let channelName = "Unknown Channel";
  try {
    const res = await fetch(oembedUrl, { signal: AbortSignal.timeout(8000) });
    if (res.ok) {
      const data = await res.json();
      title = data.title ?? title;
      channelName = data.author_name ?? channelName;
    }
  } catch {
    // fall back to defaults
  }
  return {
    videoId,
    title,
    duration: 0,
    thumbnailUrl: `https://img.youtube.com/vi/${videoId}/maxresdefault.jpg`,
    channelName,
  };
}

export function transcriptToText(entries: TranscriptEntry[]): string {
  return entries
    .map((e) => `[${formatTimestamp(e.offset)}] ${e.text}`)
    .join(" ");
}

export function formatTimestamp(seconds: number): string {
  const h = Math.floor(seconds / 3600);
  const m = Math.floor((seconds % 3600) / 60);
  const s = Math.floor(seconds % 60);
  if (h > 0) return `${h}:${String(m).padStart(2, "0")}:${String(s).padStart(2, "0")}`;
  return `${m}:${String(s).padStart(2, "0")}`;
}
