import { YoutubeTranscript } from "youtube-transcript";
import { getSubtitles } from "youtube-caption-extractor";

export interface VideoMetadata {
  videoId: string;
  title: string;
  duration: number;
  thumbnailUrl: string;
  channelName: string;
}

export interface TranscriptEntry {
  text: string;
  offset: number;
  duration: number;
}

export function extractVideoId(url: string): string | null {
  const patterns = [
    /(?:youtube\.com\/watch\?v=|youtu\.be\/|youtube\.com\/embed\/)([a-zA-Z0-9_-]{11})/,
    /^([a-zA-Z0-9_-]{11})$/,
  ];
  for (const pattern of patterns) {
    const match = url.match(pattern);
    if (match) return match[1];
  }
  return null;
}

export function validateYouTubeUrl(url: string): { valid: boolean; error?: string } {
  if (!url || url.trim() === "") {
    return { valid: false, error: "Please enter a YouTube URL." };
  }
  const videoId = extractVideoId(url);
  if (!videoId) {
    return { valid: false, error: "Invalid YouTube URL. Please use a standard youtube.com or youtu.be link." };
  }
  return { valid: true };
}

/** Map youtube-caption-extractor rows to our transcript format. */
function mapExtractorSubtitles(
  subs: { start: string; dur: string; text: string }[]
): TranscriptEntry[] {
  return subs
    .map((s) => ({
      text: s.text.trim(),
      offset: Number.parseFloat(s.start) || 0,
      duration: Math.max(0.05, Number.parseFloat(s.dur) || 0.2),
    }))
    .filter((e) => e.text.length > 0);
}

/**
 * Fallback when `youtube-transcript` breaks (YouTube HTML/API changes are common).
 * Uses InnerTube-style fetches and caption XML, including on Vercel where the old library often fails.
 */
/**
 * Default Piped API bases (comma-free origins). Public instances rotate availability;
 * we try several before failing. Override entirely with PIPED_BACKEND_URLS in production.
 * @see https://github.com/TeamPiped/Piped/wiki/List-of-instances
 */
const DEFAULT_PIPED_BACKENDS = [
  "https://pipedapi.kavin.rocks",
  "https://pipedapi.adminforge.de",
  "https://pipedapi.moomoo.me",
  "https://pipedapi.tokhmi.xyz",
  "https://api.piped.private.coffee",
];

function getPipedBackendList(): string[] {
  const fromEnv = process.env.PIPED_BACKEND_URLS?.split(",").map((s) => s.trim()).filter(Boolean);
  return fromEnv && fromEnv.length > 0 ? fromEnv : DEFAULT_PIPED_BACKENDS;
}

function isLikelyServerlessEgress(): boolean {
  return Boolean(
    process.env.VERCEL ||
      process.env.AWS_LAMBDA_FUNCTION_NAME ||
      process.env.AWS_EXECUTION_ENV ||
      process.env.K_SERVICE
  );
}

function sleep(ms: number): Promise<void> {
  return new Promise((r) => setTimeout(r, ms));
}

function ttmlTimeToSeconds(ts: string): number {
  const t = ts.trim();
  const parts = t.split(":");
  if (parts.length === 1) return parseFloat(parts[0]) || 0;
  if (parts.length === 2) return (parseInt(parts[0], 10) || 0) * 60 + (parseFloat(parts[1]) || 0);
  if (parts.length === 3) {
    return (
      (parseInt(parts[0], 10) || 0) * 3600 +
      (parseInt(parts[1], 10) || 0) * 60 +
      (parseFloat(parts[2]) || 0)
    );
  }
  return 0;
}

function decodeXmlEntities(raw: string): string {
  return raw
    .replace(/&amp;/g, "&")
    .replace(/&lt;/g, "<")
    .replace(/&gt;/g, ">")
    .replace(/&quot;/g, '"')
    .replace(/&#39;/g, "'")
    .replace(/&nbsp;/g, " ");
}

/** Parses YouTube TTML from Piped subtitle URLs (mimeType application/ttml+xml). */
function parseTtmlToTranscript(xml: string): TranscriptEntry[] {
  const out: TranscriptEntry[] = [];
  const blockRe = /<p\b([^>]+)>([\s\S]*?)<\/p>/gi;
  let m: RegExpExecArray | null;
  while ((m = blockRe.exec(xml)) !== null) {
    const begin = /(?:^|\s)begin="([^"]+)"/i.exec(m[1])?.[1];
    const end = /(?:^|\s)end="([^"]+)"/i.exec(m[1])?.[1];
    if (!begin || !end) continue;
    const start = ttmlTimeToSeconds(begin);
    const endSec = ttmlTimeToSeconds(end);
    const rawInner = m[2].replace(/<br\s*\/?>/gi, " ").replace(/<[^>]+>/g, "");
    const text = decodeXmlEntities(rawInner).replace(/\s+/g, " ").trim();
    if (!text || endSec <= start) continue;
    out.push({ text, offset: start, duration: endSec - start });
  }
  return out;
}

type PipedSubtitleTrack = {
  url: string;
  mimeType?: string;
  code?: string;
  name?: string;
  autoGenerated?: boolean;
};

/** Sort all subtitle tracks by preference (not only the best one). */
function sortPipedSubtitleTracks(tracks: PipedSubtitleTrack[]): PipedSubtitleTrack[] {
  const score = (s: PipedSubtitleTrack) => {
    const code = (s.code ?? "").toLowerCase();
    let sc = 0;
    if (code === "en" || code.startsWith("en-")) sc += 200;
    if ((s.name ?? "").toLowerCase().includes("english")) sc += 100;
    if (s.mimeType?.includes("ttml") || s.mimeType?.includes("vtt")) sc += 10;
    if (s.autoGenerated) sc -= 2;
    return sc;
  };
  return [...tracks].sort((a, b) => score(b) - score(a));
}

/** WebVTT timestamp: HH:MM:SS.mmm or MM:SS.mmm */
function parseVttTimestamp(raw: string): number {
  const t = raw.trim().split(/\s+/)[0];
  const parts = t.split(":");
  if (parts.length === 3) {
    const ms = parts[2].split(".");
    const sec = parseInt(parts[0], 10) * 3600 + parseInt(parts[1], 10) * 60 + (parseInt(ms[0], 10) || 0);
    const frac = ms[1] ? parseInt(ms[1].padEnd(3, "0").slice(0, 3), 10) / 1000 : 0;
    return sec + frac;
  }
  if (parts.length === 2) {
    const ms = parts[1].split(".");
    const sec = parseInt(parts[0], 10) * 60 + (parseInt(ms[0], 10) || 0);
    const frac = ms[1] ? parseInt(ms[1].padEnd(3, "0").slice(0, 3), 10) / 1000 : 0;
    return sec + frac;
  }
  return 0;
}

function isVttCueLine(trimmed: string): boolean {
  return trimmed.includes("-->") && /^\d/.test(trimmed);
}

/** Parse WebVTT body (Piped often serves text/vtt). Supports optional cue identifiers and NOTE blocks. */
function parseWebVttToTranscript(vtt: string): TranscriptEntry[] {
  const out: TranscriptEntry[] = [];
  const norm = vtt.replace(/\r\n/g, "\n");
  const lines = norm.split("\n");

  let i = 0;
  while (i < lines.length) {
    const line = lines[i].trim();
    if (line.startsWith("WEBVTT") || line.startsWith("NOTE") || line === "" || line.startsWith("STYLE") || line.startsWith("REGION")) {
      i++;
      continue;
    }
    if (isVttCueLine(line)) {
      const arrow = line.split("-->").map((s) => s.trim());
      if (arrow.length >= 2) {
        const start = parseVttTimestamp(arrow[0]);
        const end = parseVttTimestamp(arrow[1]);
        const textParts: string[] = [];
        i++;
        while (i < lines.length && lines[i].trim() !== "" && !isVttCueLine(lines[i].trim())) {
          textParts.push(lines[i]);
          i++;
        }
        const text = textParts.join(" ").replace(/<[^>]+>/g, " ").replace(/\s+/g, " ").trim();
        if (text && end > start) {
          out.push({ text: decodeXmlEntities(text), offset: start, duration: Math.max(0.05, end - start) });
        }
        continue;
      }
    }
    if (/^\d+$/.test(line) && i + 1 < lines.length && isVttCueLine(lines[i + 1].trim())) {
      i++;
      continue;
    }
    i++;
  }
  return out;
}

function parseSubtitlePayload(raw: string, mimeHint: string, contentType: string): TranscriptEntry[] {
  const mime = `${mimeHint} ${contentType}`.toLowerCase();
  const head = raw.trimStart().slice(0, 200).toLowerCase();
  if (mime.includes("vtt") || head.startsWith("webvtt")) {
    const v = parseWebVttToTranscript(raw);
    if (v.length > 0) return v;
  }
  if (mime.includes("ttml") || raw.trimStart().startsWith("<?xml") || raw.includes("<tt ") || raw.includes("<p ")) {
    const t = parseTtmlToTranscript(raw);
    if (t.length > 0) return t;
  }
  return [];
}

/**
 * Loads captions via a Piped-compatible API (/streams/:id → subtitle proxy URLs).
 * Often works on Vercel when direct youtube.com transcript fetches return 403/empty because
 * the proxy uses different egress than raw datacenter scrapers.
 */
async function fetchTranscriptViaPipedBackends(videoId: string): Promise<TranscriptEntry[] | null> {
  const headers = {
    Accept: "application/json",
    "User-Agent": "Lecturemate/1.0 (transcript; +https://github.com/TeamPiped/Piped)",
  };

  const backends = getPipedBackendList();
  for (let b = 0; b < backends.length; b++) {
    const apiBase = backends[b].replace(/\/$/, "");
    try {
      const streamsUrl = `${apiBase}/streams/${videoId}`;
      let res = await fetch(streamsUrl, {
        signal: AbortSignal.timeout(22000),
        headers,
      });
      if (res.status === 429 || res.status === 503) {
        await sleep(400 + b * 200);
        res = await fetch(streamsUrl, { signal: AbortSignal.timeout(22000), headers });
      }
      if (!res.ok) continue;
      const data = (await res.json()) as { subtitles?: PipedSubtitleTrack[]; error?: string };
      if (data.error || !data.subtitles?.length) continue;

      const ordered = sortPipedSubtitleTracks(data.subtitles);
      for (const track of ordered.slice(0, 6)) {
        if (!track?.url) continue;
        try {
          const subRes = await fetch(track.url, {
            signal: AbortSignal.timeout(50000),
            headers: { ...headers, Accept: "*/*" },
          });
          if (!subRes.ok) continue;
          const raw = await subRes.text();
          if (!raw.trim()) continue;
          const ct = subRes.headers.get("content-type") ?? "";
          const entries = parseSubtitlePayload(raw, track.mimeType ?? "", ct);
          if (entries.length > 0) return entries;
        } catch {
          /* next track */
        }
      }
    } catch {
      /* try next backend */
    }
  }
  return null;
}

async function fetchTranscriptViaExtractor(videoId: string): Promise<TranscriptEntry[] | null> {
  const languagesToTry = [
    "en",
    "en-US",
    "en-GB",
    "hi",
    "bn",
    "ta",
    "te",
    "mr",
    "gu",
    "kn",
    "ml",
    "es",
    "fr",
    "de",
    "pt",
    "it",
    "nl",
    "pl",
    "ru",
    "uk",
    "zh",
    "zh-Hans",
    "ja",
    "ko",
    "vi",
    "th",
    "id",
    "ar",
    "tr",
  ];
  for (const lang of languagesToTry) {
    try {
      const subs = await getSubtitles({ videoID: videoId, lang });
      if (subs.length > 0) return mapExtractorSubtitles(subs);
    } catch {
      /* try next language */
    }
  }
  return null;
}

export async function fetchTranscript(videoId: string): Promise<TranscriptEntry[]> {
  // Try a sequence of language tracks before giving up.
  // Many lectures have auto-generated captions in the original language but not English.
  const languagesToTry = ["en", "en-US", "en-GB", "es", "fr", "de", "hi", "zh", "ja", "ko", "pt", "ru"];

  let lastError: unknown = null;

  // 1. Prefer default track first (youtube-transcript)
  try {
    const transcript = await YoutubeTranscript.fetchTranscript(videoId);
    if (transcript.length > 0) {
      return transcript.map((entry) => ({
        text: entry.text,
        offset: entry.offset / 1000,
        duration: entry.duration / 1000,
      }));
    }
  } catch (err) {
    lastError = err;
  }

  // 2. Try each language explicitly
  for (const lang of languagesToTry) {
    try {
      const transcript = await YoutubeTranscript.fetchTranscript(videoId, { lang });
      if (transcript.length > 0) {
        return transcript.map((entry) => ({
          text: entry.text,
          offset: entry.offset / 1000,
          duration: entry.duration / 1000,
        }));
      }
    } catch (err) {
      lastError = err;
    }
  }

  // 3. Piped proxy path (before caption-extractor): different egress; often works on Vercel when YouTube blocks datacenter IPs.
  try {
    const viaPiped = await fetchTranscriptViaPipedBackends(videoId);
    if (viaPiped && viaPiped.length > 0) return viaPiped;
  } catch (err) {
    lastError = err;
  }

  // 4. youtube-caption-extractor (InnerTube-style; can still fail on strict blocks)
  try {
    const viaExtractor = await fetchTranscriptViaExtractor(videoId);
    if (viaExtractor && viaExtractor.length > 0) return viaExtractor;
  } catch (err) {
    lastError = err;
  }

  // 5. Second Piped pass after cooldown (rate limits / transient 5xx)
  if (isLikelyServerlessEgress()) {
    try {
      await sleep(900);
      const viaPiped2 = await fetchTranscriptViaPipedBackends(videoId);
      if (viaPiped2 && viaPiped2.length > 0) return viaPiped2;
    } catch (err) {
      lastError = err;
    }
  }

  // 6. Friendly error
  const msg = lastError instanceof Error ? lastError.message : String(lastError);
  if (msg.includes("private") || msg.includes("unavailable")) {
    throw new Error("This video is private or unavailable. Try a public video.");
  }
  throw new Error(
    "We could not download captions for this video. YouTube often blocks or rate-limits transcript fetches from cloud servers even when CC is visible in the browser. Fix: set PIPED_BACKEND_URLS to one or more reachable Piped API bases (comma-separated, see .env.example), self-host Piped for reliability, wait and retry, or run the app from localhost for development."
  );
}

export async function fetchVideoMetadata(videoId: string): Promise<VideoMetadata> {
  // Use oEmbed API (no API key required) for title/channel
  const oembedUrl = `https://www.youtube.com/oembed?url=https://www.youtube.com/watch?v=${videoId}&format=json`;
  
  let title = "YouTube Lecture";
  let channelName = "Unknown Channel";

  try {
    const res = await fetch(oembedUrl, { signal: AbortSignal.timeout(8000) });
    if (res.ok) {
      const data = await res.json();
      title = data.title ?? title;
      channelName = data.author_name ?? channelName;
    }
  } catch {
    // fallback to defaults
  }

  return {
    videoId,
    title,
    duration: 0,
    thumbnailUrl: `https://img.youtube.com/vi/${videoId}/maxresdefault.jpg`,
    channelName,
  };
}

export function transcriptToText(entries: TranscriptEntry[]): string {
  return entries
    .map((e) => `[${formatTimestamp(e.offset)}] ${e.text}`)
    .join(" ");
}

export function formatTimestamp(seconds: number): string {
  const h = Math.floor(seconds / 3600);
  const m = Math.floor((seconds % 3600) / 60);
  const s = Math.floor(seconds % 60);
  if (h > 0) return `${h}:${String(m).padStart(2, "0")}:${String(s).padStart(2, "0")}`;
  return `${m}:${String(s).padStart(2, "0")}`;
}
