import { YoutubeTranscript } from "youtube-transcript";
import { getSubtitles } from "youtube-caption-extractor";

export interface VideoMetadata {
  videoId: string;
  title: string;
  duration: number;
  thumbnailUrl: string;
  channelName: string;
}

export interface TranscriptEntry {
  text: string;
  offset: number;
  duration: number;
}

export function extractVideoId(url: string): string | null {
  const patterns = [
    /(?:youtube\.com\/watch\?v=|youtu\.be\/|youtube\.com\/embed\/)([a-zA-Z0-9_-]{11})/,
    /^([a-zA-Z0-9_-]{11})$/,
  ];
  for (const pattern of patterns) {
    const match = url.match(pattern);
    if (match) return match[1];
  }
  return null;
}

export function validateYouTubeUrl(url: string): { valid: boolean; error?: string } {
  if (!url || url.trim() === "") {
    return { valid: false, error: "Please enter a YouTube URL." };
  }
  const videoId = extractVideoId(url);
  if (!videoId) {
    return { valid: false, error: "Invalid YouTube URL. Please use a standard youtube.com or youtu.be link." };
  }
  return { valid: true };
}

/** Map youtube-caption-extractor rows to our transcript format. */
function mapExtractorSubtitles(
  subs: { start: string; dur: string; text: string }[]
): TranscriptEntry[] {
  return subs
    .map((s) => ({
      text: s.text.trim(),
      offset: Number.parseFloat(s.start) || 0,
      duration: Math.max(0.05, Number.parseFloat(s.dur) || 0.2),
    }))
    .filter((e) => e.text.length > 0);
}

/**
 * Fallback when `youtube-transcript` breaks (YouTube HTML/API changes are common).
 * Uses InnerTube-style fetches and caption XML, including on Vercel where the old library often fails.
 */
/** Default Piped API host (public instance; override with PIPED_BACKEND_URLS). */
const DEFAULT_PIPED_BACKENDS = ["https://api.piped.private.coffee"];

function getPipedBackendList(): string[] {
  const fromEnv = process.env.PIPED_BACKEND_URLS?.split(",").map((s) => s.trim()).filter(Boolean);
  return fromEnv && fromEnv.length > 0 ? fromEnv : DEFAULT_PIPED_BACKENDS;
}

function ttmlTimeToSeconds(ts: string): number {
  const t = ts.trim();
  const parts = t.split(":");
  if (parts.length === 1) return parseFloat(parts[0]) || 0;
  if (parts.length === 2) return (parseInt(parts[0], 10) || 0) * 60 + (parseFloat(parts[1]) || 0);
  if (parts.length === 3) {
    return (
      (parseInt(parts[0], 10) || 0) * 3600 +
      (parseInt(parts[1], 10) || 0) * 60 +
      (parseFloat(parts[2]) || 0)
    );
  }
  return 0;
}

function decodeXmlEntities(raw: string): string {
  return raw
    .replace(/&amp;/g, "&")
    .replace(/&lt;/g, "<")
    .replace(/&gt;/g, ">")
    .replace(/&quot;/g, '"')
    .replace(/&#39;/g, "'")
    .replace(/&nbsp;/g, " ");
}

/** Parses YouTube TTML from Piped subtitle URLs (mimeType application/ttml+xml). */
function parseTtmlToTranscript(xml: string): TranscriptEntry[] {
  const out: TranscriptEntry[] = [];
  const blockRe = /<p\b([^>]+)>([\s\S]*?)<\/p>/gi;
  let m: RegExpExecArray | null;
  while ((m = blockRe.exec(xml)) !== null) {
    const begin = /(?:^|\s)begin="([^"]+)"/i.exec(m[1])?.[1];
    const end = /(?:^|\s)end="([^"]+)"/i.exec(m[1])?.[1];
    if (!begin || !end) continue;
    const start = ttmlTimeToSeconds(begin);
    const endSec = ttmlTimeToSeconds(end);
    const rawInner = m[2].replace(/<br\s*\/?>/gi, " ").replace(/<[^>]+>/g, "");
    const text = decodeXmlEntities(rawInner).replace(/\s+/g, " ").trim();
    if (!text || endSec <= start) continue;
    out.push({ text, offset: start, duration: endSec - start });
  }
  return out;
}

type PipedSubtitleTrack = {
  url: string;
  mimeType?: string;
  code?: string;
  name?: string;
  autoGenerated?: boolean;
};

function pickPipedSubtitleTrack(tracks: PipedSubtitleTrack[]): PipedSubtitleTrack | null {
  if (!tracks.length) return null;
  const score = (s: PipedSubtitleTrack) => {
    const code = (s.code ?? "").toLowerCase();
    let sc = 0;
    if (code === "en" || code.startsWith("en-")) sc += 200;
    if ((s.name ?? "").toLowerCase().includes("english")) sc += 100;
    if (s.mimeType?.includes("ttml")) sc += 10;
    if (s.autoGenerated) sc -= 2;
    return sc;
  };
  return [...tracks].sort((a, b) => score(b) - score(a))[0];
}

/**
 * Loads captions via a Piped-compatible API (/streams/:id → subtitle proxy URLs).
 * Often works on Vercel when direct youtube.com transcript fetches return 403/empty because
 * the proxy uses different egress than raw datacenter scrapers.
 */
async function fetchTranscriptViaPipedBackends(videoId: string): Promise<TranscriptEntry[] | null> {
  const headers = { Accept: "application/json", "User-Agent": "Lecturemate/1.0" };

  for (const base of getPipedBackendList()) {
    const apiBase = base.replace(/\/$/, "");
    try {
      const streamsUrl = `${apiBase}/streams/${videoId}`;
      const res = await fetch(streamsUrl, {
        signal: AbortSignal.timeout(18000),
        headers,
      });
      if (!res.ok) continue;
      const data = (await res.json()) as { subtitles?: PipedSubtitleTrack[]; error?: string };
      if (data.error || !data.subtitles?.length) continue;

      const track = pickPipedSubtitleTrack(data.subtitles);
      if (!track?.url) continue;

      const subRes = await fetch(track.url, { signal: AbortSignal.timeout(45000), headers });
      if (!subRes.ok) continue;
      const raw = await subRes.text();
      if (!raw.trim()) continue;

      const mime = track.mimeType ?? subRes.headers.get("content-type") ?? "";
      if (mime.includes("ttml") || raw.trimStart().startsWith("<?xml") || raw.includes("<tt ")) {
        const entries = parseTtmlToTranscript(raw);
        if (entries.length > 0) return entries;
      }
    } catch {
      /* try next backend */
    }
  }
  return null;
}

async function fetchTranscriptViaExtractor(videoId: string): Promise<TranscriptEntry[] | null> {
  const languagesToTry = [
    "en",
    "en-US",
    "en-GB",
    "hi",
    "bn",
    "ta",
    "te",
    "mr",
    "gu",
    "kn",
    "ml",
    "es",
    "fr",
    "de",
    "pt",
    "it",
    "nl",
    "pl",
    "ru",
    "uk",
    "zh",
    "zh-Hans",
    "ja",
    "ko",
    "vi",
    "th",
    "id",
    "ar",
    "tr",
  ];
  for (const lang of languagesToTry) {
    try {
      const subs = await getSubtitles({ videoID: videoId, lang });
      if (subs.length > 0) return mapExtractorSubtitles(subs);
    } catch {
      /* try next language */
    }
  }
  return null;
}

export async function fetchTranscript(videoId: string): Promise<TranscriptEntry[]> {
  // Try a sequence of language tracks before giving up.
  // Many lectures have auto-generated captions in the original language but not English.
  const languagesToTry = ["en", "en-US", "en-GB", "es", "fr", "de", "hi", "zh", "ja", "ko", "pt", "ru"];

  let lastError: unknown = null;

  // 1. Prefer default track first (youtube-transcript)
  try {
    const transcript = await YoutubeTranscript.fetchTranscript(videoId);
    if (transcript.length > 0) {
      return transcript.map((entry) => ({
        text: entry.text,
        offset: entry.offset / 1000,
        duration: entry.duration / 1000,
      }));
    }
  } catch (err) {
    lastError = err;
  }

  // 2. Try each language explicitly
  for (const lang of languagesToTry) {
    try {
      const transcript = await YoutubeTranscript.fetchTranscript(videoId, { lang });
      if (transcript.length > 0) {
        return transcript.map((entry) => ({
          text: entry.text,
          offset: entry.offset / 1000,
          duration: entry.duration / 1000,
        }));
      }
    } catch (err) {
      lastError = err;
    }
  }

  // 3. Robust fallback (often works when CC is visible but youtube-transcript fails)
  try {
    const viaExtractor = await fetchTranscriptViaExtractor(videoId);
    if (viaExtractor && viaExtractor.length > 0) return viaExtractor;
  } catch (err) {
    lastError = err;
  }

  // 4. Piped proxy path — often succeeds on hosted servers where YouTube blocks direct fetches (e.g. Vercel).
  try {
    const viaPiped = await fetchTranscriptViaPipedBackends(videoId);
    if (viaPiped && viaPiped.length > 0) return viaPiped;
  } catch (err) {
    lastError = err;
  }

  // 5. Friendly error
  const msg = lastError instanceof Error ? lastError.message : String(lastError);
  if (msg.includes("private") || msg.includes("unavailable")) {
    throw new Error("This video is private or unavailable. Try a public video.");
  }
  throw new Error(
    "We could not download captions for this video. Server-side transcript services are sometimes blocked or rate-limited even when YouTube shows CC. Set PIPED_BACKEND_URLS in env to a reachable Piped API, try again later, or test from localhost."
  );
}

export async function fetchVideoMetadata(videoId: string): Promise<VideoMetadata> {
  // Use oEmbed API (no API key required) for title/channel
  const oembedUrl = `https://www.youtube.com/oembed?url=https://www.youtube.com/watch?v=${videoId}&format=json`;
  
  let title = "YouTube Lecture";
  let channelName = "Unknown Channel";

  try {
    const res = await fetch(oembedUrl, { signal: AbortSignal.timeout(8000) });
    if (res.ok) {
      const data = await res.json();
      title = data.title ?? title;
      channelName = data.author_name ?? channelName;
    }
  } catch {
    // fallback to defaults
  }

  return {
    videoId,
    title,
    duration: 0,
    thumbnailUrl: `https://img.youtube.com/vi/${videoId}/maxresdefault.jpg`,
    channelName,
  };
}

export function transcriptToText(entries: TranscriptEntry[]): string {
  return entries
    .map((e) => `[${formatTimestamp(e.offset)}] ${e.text}`)
    .join(" ");
}

export function formatTimestamp(seconds: number): string {
  const h = Math.floor(seconds / 3600);
  const m = Math.floor((seconds % 3600) / 60);
  const s = Math.floor(seconds % 60);
  if (h > 0) return `${h}:${String(m).padStart(2, "0")}:${String(s).padStart(2, "0")}`;
  return `${m}:${String(s).padStart(2, "0")}`;
}
